<#!
Create a distributable installer package for Windows.

This script prepares a staging folder, optionally downloads the PSAppDeployToolkit,
copies the repository files required to run Saffin, creates a simple Deploy-Application
wrapper (when PSADT is used), and packages everything into a ZIP at `dist/SaffinInstaller.zip`.

Usage (from repo root):
  .\scripts\package_installer.ps1                 # create ZIP installer (default)
  .\scripts\package_installer.ps1 -UsePSADT       # include PSAppDeployToolkit and Deploy-Application.ps1
  .\scripts\package_installer.ps1 -OutputPath .\dist\SaffinInstaller.zip -CreateReadmeOnly

Notes:
- This creates a portable ZIP. For a true EXE/MSI you can combine this with 7-Zip SFX
  or use PSADT tooling to build an executable installer from the staged folder.
- If you pass `-UsePSADT`, the script will download PSAppDeployToolkit automatically.
  The generated `Deploy-Application.ps1` is a lightweight wrapper that calls the
  included `scripts\start_saffin.ps1` and helper scripts to create shortcuts and tasks.
#>

[CmdletBinding()]
param(
    [string]$OutputPath = '.\dist\SaffinInstaller.zip',
    [switch]$UsePSADT,
    [switch]$CreateReadmeOnly
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$root = (Resolve-Path "$PSScriptRoot\..").Path
$timestamp = Get-Date -Format yyyyMMddHHmmss
$staging = Join-Path ([IO.Path]::GetTempPath()) ("saffin_installer_$timestamp")
New-Item -ItemType Directory -Path $staging | Out-Null

Write-Host "Staging directory: $staging"

function Invoke-Download($url, $dest) {
    Write-Host "Downloading: $url -> $dest"
    try {
        Invoke-WebRequest -Uri $url -OutFile $dest -UseBasicParsing -ErrorAction Stop
    } catch {
        throw "Failed to download $url : $_"
    }
}

if ($UsePSADT) {
    $psadtUrl = 'https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/releases/latest/download/PSAppDeployToolkit.zip'
    $toolsDir = Join-Path $staging 'PSAppDeployToolkit'
    New-Item -ItemType Directory -Path $toolsDir | Out-Null
    $zipPath = Join-Path $staging 'PSAppDeployToolkit.zip'
    Invoke-Download $psadtUrl $zipPath
    Expand-Archive -Path $zipPath -DestinationPath $toolsDir
    Remove-Item $zipPath
}

# Copy repository files to staging (exclude large or irrelevant folders)
$excludes = @('.git', '.venv', 'dist', '.github', '__pycache__')
Write-Host 'Copying project files to staging (this may take a few seconds)...'
Get-ChildItem -Path $root -Force | ForEach-Object {
    $name = $_.Name
    if ($excludes -contains $name) { return }
    if ($name -eq 'dist') { return }
    $target = Join-Path $staging $name
    if ($_.PSIsContainer) {
        Copy-Item -Path $_.FullName -Destination $target -Recurse -Force -ErrorAction SilentlyContinue
    } else {
        Copy-Item -Path $_.FullName -Destination $target -Force -ErrorAction SilentlyContinue
    }
}

if ($UsePSADT) {
    # Create a minimal Deploy-Application.ps1 wrapper that calls our helper scripts
    $deployPath = Join-Path $staging 'PSAppDeployToolkit\Deploy-Application.ps1'
    $deployContent = @'
# Minimal Deploy-Application wrapper for Saffin
## This file was generated by scripts/package_installer.ps1
Write-Host "Running Saffin installer wrapper..."
# Ensure scripts run from the package root
Push-Location (Split-Path -Parent $MyInvocation.MyCommand.Path)

# Install dependencies and create shortcuts/tasks
Write-Host "Installing dependencies and creating shortcuts..."
try {
    & "./scripts/start_saffin.ps1" -InstallDeps -WithEmbeddings
} catch {
    Write-Warning "Failed to run start_saffin.ps1: $_"
}

try {
    & "./scripts/create_desktop_shortcut.ps1" -Name 'Saffin Assistant'
} catch {
    Write-Warning "Failed to create desktop shortcut: $_"
}

try {
    & "./scripts\schedule_reminder.ps1" -TaskName 'SaffinMorning' -Time '09:00' -Message 'Log your session for today'
} catch {
    Write-Warning "Failed to schedule reminder: $_"
}

Pop-Location
'@
    $deployContent | Out-File -FilePath $deployPath -Encoding UTF8 -Force
}

if ($CreateReadmeOnly) {
    $readme = @"
Saffin Installer package created at: $staging

Run the installer by extracting the ZIP and running `scripts\start_saffin.ps1` or
`PSAppDeployToolkit\Deploy-Application.ps1` (when PSADT is included).
"@
    $readmePath = Join-Path $staging 'INSTALL_README.txt'
    $readme | Out-File -FilePath $readmePath -Encoding UTF8
}

# Ensure output directory exists
$outDir = Split-Path -Parent $OutputPath
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }

Write-Host "Creating ZIP: $OutputPath"
if (Test-Path $OutputPath) { Remove-Item $OutputPath -Force }
Compress-Archive -Path (Join-Path $staging '*') -DestinationPath $OutputPath -Force

Write-Host "Package created: $OutputPath"
Write-Host "Staging folder (left for inspection): $staging"
Write-Host "To create an EXE SFX installer, you can use 7-Zip's SFX modules or PSADT packaging tools locally."
